import { DocumentRequestType } from './document-templates.config';

/**
 * Realistic Bulgarian dummy data for generating sample/образец document previews.
 * Each entry must satisfy the requiredFields + validation logic of its document type.
 */
export const SAMPLE_DATA: Record<DocumentRequestType, Record<string, any>> = {
 speciment: {
  three_names: 'Иван Петров Георгиев',
  egn: '8501011234',
  id_number: '645123789',
  id_year: '2020-03-15',
  id_issuer: 'МВР София',
  company_name: 'Примерна Компания ЕООД',
  company_adress: 'гр. София, бул. Витоша №100',
  email: 'sample@gotovdoc.bg',
 },

 mps_power_of_attorney: {
  principal_full_name: 'Георги Димитров Стоянов',
  principal_egn: '7503152345',
  principal_id_number: '645678901',
  principal_id_issue_date: '2020-05-10',
  principal_id_issuer: 'МВР Пловдив',
  principal_address: 'гр. Пловдив, ул. Княз Борис I №15',
  authorized_full_name: 'Мария Иванова Петрова',
  authorized_egn: '9012203456',
  authorized_id_number: '756789012',
  authorized_id_issue_date: '2021-03-22',
  authorized_id_issuer: 'МВР Варна',
  authorized_address: 'гр. Варна, бул. Приморски №42',
  car_type: 'лек автомобил',
  car_make_model: 'Toyota Corolla',
  car_registration_number: 'СА 1234 ВК',
  car_vin: 'JTDBR32E960012345',
  car_engine_number: '1ZR-FE-1234567',
  car_color: 'сребрист',
  date: '2025-01-15',
  place: 'София',
  email: 'sample@gotovdoc.bg',
 },

 leave_request: {
  company_name: 'Примерна Компания ЕООД',
  employee_full_name: 'Иван Петров Георгиев',
  employee_position: 'Софтуерен инженер',
  leave_type: 'платен',
  leave_days: '10',
  start_date: '2025-03-01',
  request_date: '2025-02-15',
  email: 'sample@gotovdoc.bg',
 },

 loan_agreement: {
  lender_type: 'ФИЗИЧЕСКО ЛИЦЕ',
  borrower_type: 'ФИЗИЧЕСКО ЛИЦЕ',
  lender_full_name: 'Георги Димитров Стоянов',
  lender_egn: '7503152345',
  lender_id_number: '645678901',
  lender_id_issue_date: '2020-05-10',
  lender_id_issuer: 'МВР Пловдив',
  lender_address: 'гр. Пловдив, ул. Княз Борис I №15',
  borrower_full_name: 'Мария Иванова Петрова',
  borrower_egn: '9012203456',
  borrower_id_number: '756789012',
  borrower_id_issue_date: '2021-03-22',
  borrower_id_issuer: 'МВР Варна',
  borrower_address: 'гр. Варна, бул. Приморски №42',
  contract_date: '2025-01-15',
  contract_city: 'София',
  loan_amount: '5000',
  interest_rate: '3.5',
  return_date: '2026-01-15',
  payment_method: 'в брой',
  return_method: 'в брой',
  email: 'sample@gotovdoc.bg',
 },

 source_of_funds_declaration: {
  declarant_type: 'ФИЗИЧЕСКО ЛИЦЕ',
  firstName: 'Иван',
  middleName: 'Петров',
  lastName: 'Георгиев',
  egn: '8501011234',
  citizenship: 'българско',
  id_number: '645123789',
  id_issue_date: '2020-03-15',
  id_issuer: 'МВР София',
  declarant_city: 'София',
  address: 'гр. София, бул. Витоша №100',
  declaration_date: '2025-01-20',
  amount: '15000',
  transaction_subject: 'Покупка на недвижим имот',
  funds_source: 'Спестявания от трудова дейност',
  email: 'sample@gotovdoc.bg',
 },

 employment_contract: {
  company_name: 'Примерна Компания ЕООД',
  company_eik: '123456789',
  company_city: 'София',
  company_address: 'бул. Витоша №100',
  employer_representative_name: 'Петър Стоянов Димитров',
  employer_representative_egn: '6802153456',
  employee_firstName: 'Иван',
  employee_middleName: 'Петров',
  employee_lastName: 'Георгиев',
  employee_egn: '8501011234',
  employee_id_number: '645123789',
  employee_id_issue_date: '2020-03-15',
  employee_id_issuer: 'МВР София',
  employee_city: 'София',
  employee_address: 'ул. Граф Игнатиев №25',
  contract_date: '2025-02-01',
  contract_city: 'София',
  nkpd_code: '25121048',
  workplace: 'гр. София, бул. Витоша №100',
  start_date: '2025-03-01',
  contract_term: 'без срок',
  probation_period: 'без изпитване',
  salary: '3500',
  working_hours_per_day: '8',
  working_days_per_week: '5',
  paid_leave_days: '20',
  email: 'sample@gotovdoc.bg',
 },

 job_resignation_request: {
  company_name: 'Примерна Компания ЕООД',
  employee_full_name: 'Иван Петров Георгиев',
  employee_egn: '8501011234',
  employee_position: 'Софтуерен инженер',
  request_date: '2025-02-15',
  email: 'sample@gotovdoc.bg',
 },

 criminal_record_certificate: {
  applicant_full_name: 'Иван Петров Георгиев',
  applicant_egn: '8501011234',
  birth_date: '1985-01-01',
  birth_place: 'гр. София',
  address: 'гр. София, бул. Витоша №100',
  mother_name: 'Елена Иванова Георгиева',
  father_name: 'Петър Иванов Георгиев',
  court_name: 'Софийски районен съд',
  purpose: 'Постъпване на работа',
  application_city: 'София',
  application_date: '2025-01-20',
  email: 'sample@gotovdoc.bg',
 },
};
